project:
  type: website
  output-dir: docs
  
website:
  title: "tinan2001.github.io"
  navbar:
    left:
      - text: Home 
        href: index.qmd
  
      - text: Resume
        href: resume.qmd
        
      - text: Past Projects
        menu:
          - text: Advance Remote Sensing
          - href: GEO653.qmd
          - text: GIS in Env. Modeling
          - href: GEO559.qmd
        
      
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



