project:
  type: website
  output-dir: docs
  
website:
  title: "Tina Ni"
  navbar:
    left:
      - text: About Me
        href: index.qmd
  
      - text: Resume
        href: resume.qmd
        
      - text: Masters Portfolio
        menu:
          - text: Personal Statement
          - href: personalstatement.qmd
          - text: Resume
          - href: resume.qmd
          - text: Writing Sample
          - href: writingsample.qmd
          - text: Technical Application
          - href: GEO653.qmd
        
      - text: Past Projects
        menu:
          - text: Advance Remote Sensing
          - href: GEO653.qmd
          - text: GIS in Env. Modeling
          - href: GEO559.qmd
          - text: Machine Learning in GIS (ongoing)
          - href: GEO514.qmd
          - text: Dynmaic Modeling
          - href: GEO593.qmd
        
      
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true