project:
  type: website
  output-dir: docs

website:
  title: "Tina Ni"
  navbar:
    left:
      - text: About Me
        href: index.qmd

      - text: Resume
        href: resume.qmd

      - text: Masters Portfolio
        menu:
          - text: Personal Statement
            href: personalstatement.html
          - text: Resume
            href: resume.html
          - text: Writing Sample
            href: writingsample.html
          - text: Technical Application
            href: GEO653.html
            
      - text: Past Projects
        menu:
          - text: Advanced Remote Sensing
            href: GEO653.html
          - text: GIS in Env. Modeling
            href: GEO559.html
          - text: Machine Learning in GIS (ongoing)
            href: GEO514.html
          - text: Dynamic Modeling
            href: GEO593.html

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    format:
    code-fold: true
    code-tools: true
    grid:
      body-width: 1000px
      sidebar-width: 250px
      margin-width: 150px

