---
title: Academic Personal Statement
date: "`r format(Sys.time(), '%B %Y')`"

format:
  html:
    code-fold: false
    code-tools: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

When I first applied to the graduate Geographic Information Science program at the University at Buffalo, my initial goal was to learn new GIS skills that would be applicable to my environmental profession. At that time, my main area of interest was invasive species management and saw GIS as a critical tool to help model and further understand and solve the environment and the problems respected to it Now, after almost completing three semesters the GIS program, I can confidently say that my initial goals coming into the program were achieved but also expanded upon. The graduate program along with the faculty, staff, and colleagues have strengthen my technical GIS skills, my insights on geographical and spatial analysis, interpretation, problem solving skills, and broaden my perspective on the role of GIS across various disciplines.

Through the coursework, I have been able to broaden my perspective on the utilization of GIS in various professional sectors. The spectrum has expanded from environmental monitoring to urban planning and to transportation. The exposure to other professional fields, that also relied on GIS, allowed me to look further than a professional career in the environmental field. Understanding the critical role that GIS has in different sectors has shifted my professional goals to a broader emphasis on spatial science careers. Especially with the ongoing technological improvements and governmental defunding of environmental careers, I see myself - after three semesters, finding myself wanting to use GIS in a professional setting as an essential tool to analyze and improve systems connecting people to the environmental.

The fundamental classes such as uni and multi-variant statistics has provided me with an essential baseline to spatial analysis. After taking these classes, there were many instances where I used the statistics that I've learned, to understand problems and create solutions. Without these classes, I would not to be able to excel at the advance coursework that would allow me to showcase my work to professionals. When I selected my elective courses, the program offered a diverse course log that ranged from remote sensing, AI, to transportation. The two areas that I believe became the central to my degree were remote sensing and spatial programming. Both topics incorporated statistics and data analysis at a more advanced level, allowing me to think beyond typical GIS applications and popular GIS tools such as ESRI software. These classes allowed me to create new programs to identify and solve issues. With how advanced society has become- relying more on data and computer driven models, remote sensing and spatial programming assisted in my path to more demanding data science professions.

Overall, after completing graduate geographic information science program, I can confidently say that the program and the GIS community at UB has prepared me to think and solve issues in both a professional and social setting. By the end of this program, I will have gained stronger analytical, technical, and critical thinking skills to solve issues related to both human and nonhuman environmental systems.

Not only has this graduate program helped me achieve my original goal to learn more GIS skills for the environmental problems but it has also created new goals for me to better our society and our communities. As I leave the department and set out into my professional career, I exit this program with a confident and respected understanding of GIS that is viewed as a way to connect communities, environments, and society with technology and data. The geographic information science graduate program has equipped me to move from the academic setting into the professional world with vital tools to understand systems and structures spatially- allowing me to improve communities and society.
