---
title: Academic Personal Statement
---

When I first applied to the graduate Geographic Information Science program at the University at Buffalo, my initial goal was to learn new GIS skills that would be applicable to my environmental profession. At that time, my main area of interest was invasive species management, which I viewed GIS as a critical tool to help model, further understand, and solve environmental problems. Now, after almost completing three semesters in the GIS program, I can confidently say that the program has fulfilled my initial goals and much more. The graduate program, along with the faculty, staff, and colleagues, has strengthened my technical GIS skills, my insights on geographical and spatial analysis, interpretation, and problem-solving skills, and broadened my perspective on the role of GIS across various disciplines.

Through the coursework, I have been able to broaden my perspective on the utilization of GIS in various professional sectors. The spectrum has expanded from environmental monitoring to urban planning and transportation. The exposure to other professional fields that also rely on GIS allowed me to look beyond a career solely in the environmental field. Understanding the critical role that GIS plays in different sectors has shifted my professional goals to a broader emphasis on spatial science careers. Especially with ongoing technological improvements and governmental defunding of environmental careers, I see myself wanting to use GIS in a professional setting as an essential tool to analyze and improve systems connecting people to the environment.

The fundamental classes, such as uni- and multi-variate statistics, have provided me with an essential baseline for spatial analysis. After taking these classes, there were many instances where I applied the statistics I learned to understand problems and create solutions. Without these classes, I would not have been able to excel in the advanced coursework that allowed me to showcase my work to professionals. When I selected my elective courses, the program offered a diverse course catalog that ranged from remote sensing to artificial intelligence. The two areas that became central to my degree were remote sensing and spatial programming. Both topics incorporated statistics and data analysis at a more advanced level, allowing me to think beyond typical GIS applications and popular software tools such as ESRI Arc GIS Pro. These classes enabled me to create new programs to identify and solve issues. With society relying increasingly on data and computer-driven models, remote sensing and spatial programming have helped prepare me for more demanding data science professions.

Overall, after completing the graduate Geographic Information Science program, I can confidently say that the program and the GIS community at UB have prepared me to think critically and solve issues in both professional and social settings. By the end of this program, I will have gained stronger analytical, technical, and critical thinking skills to address challenges related to both human and nonhuman environmental systems.

Not only has this graduate program helped me achieve my original goal of learning GIS skills to address environmental problems, but it has also created new goals for me to improve our society and communities. As I leave the department and resume my professional career, I exit this program with a confident and respected understanding of GIS to connect communities, environments, and society through technology and data. The Geographic Information Science graduate program has equipped me to move from the academic setting into the professional world with the tools to understand systems and structures spatially- allowing me to make meaningful improvements in communities and society.
